import { Toaster } from "@/components/ui/toaster";
import { Search } from "lucide-react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import Logo from "../../public/images/Hekto.png";
import BottomFooter from "../components/BottomFooter";
import Footer from "../components/Footer";
import TopHeader from "../components/TopHeader";
import "./globals.css";
import Link from "next/link";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* {children} */}
        <TopHeader />



        <header className="py-4">
          <nav className="container mx-auto flex justify-between items-center">
            <Image
              src={Logo} // Replace with your logo file path
              alt="Logo"
              className="mr-2"
            />
            <Link  href="/" className="text-lg font-bold">
              Home
            </Link>
            <Link  href="/shop" className="text-lg font-bold">
              Products
            </Link>
            <Link  href="/" className="text-lg font-bold">
              Blogs
            </Link>
            <Link  href="/contact" className="text-lg font-bold">
              Contact
            </Link>
            <div className="w-72 flex">

              <input
                type="text"
                placeholder="Search"
                className="w-full px-4 py-2 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-pink-500"
              />
              <button
                type="button"
                className="bg-pink-500 p-2 flex items-center justify-center hover:bg-pink-600"
              >
                <Search className="text-white w-5 h-5" />
              </button>
            </div>


          </nav>
        </header>
        <main>{children}</main>
        <Toaster />
        <Footer />
        <BottomFooter />

      </body>
    </html>
  );
}
